# Generated by Django 6.0.3 on 2026-03-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_department_head_of_department_subject_description_and_more'),
        ('faculty', '0002_event_holiday_timetable'),
    ]

    operations = [
    ]
