# Generated by Django 6.0.3 on 2026-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
