# Generated by Django 6.0.3 on 2026-04-01 15:41

import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=32, unique=True),
        ),
    ]
